### ISSUE TITLE
I can't run the code which is data_process

### ISSUE THREAD

**Issue by code-monsters-lgl** [jingyaogong/minimind#14]
- 运行`data_process.py`的时候，数据集使用的是`sft_data_zh.jsonl`，报错信息如下：请问这个bug怎么解决？感谢！😂🤗

```python：
Traceback (most recent call last):
  File "D:\program\python\anaconda\envs\llm\lib\site-packages\jsonlines\jsonlines.py", line 326, in read
    value: JSONValue = self._loads(line)
orjson.JSONDecodeError: unexpected end of data: line 1 column 318 (char 317)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\lgl\llm\minimind-master\data_process.py", line 207, in <module>
    sft_process(contain_history=True)
  File "D:\lgl\llm\minimind-master\data_process.py", line 152, in sft_process
    for idx, obj in enumerate(reader):
  File "D:\program\python\anaconda\envs\llm\lib\site-packages\jsonlines\jsonlines.py", line 434, in iter
    yield self.read(
  File "D:\program\python\anaconda\envs\llm\lib\site-packages\jsonlines\jsonlines.py", line 331, in read
    raise exc from orig_exc
jsonlines.jsonlines.InvalidLineError: line contains invalid json: unexpected end of data: line 1 column 318 (char 317) (line 1182414)
```

报错部分的代码如下：
![image](https://github.com/user-attachments/assets/f6bff8b8-1055-4035-b44d-b730b682b5f8)

**Comment by jingyaogong** [comment]
我不确定是不是jsonl文件损坏，文件确实比较大。我这是正常的

如果只是特定行损坏或者编码有问题，加
```python
try:
    # ..
except:
    continue
```
跳过这部分数据。

此外，我这里有data_process完成的sft_data.csv文件（但是只保留了<=256长度的内容）可以直接下载使用免data_process

> _single.csv没有历史对话，_multi.csv有历史对话。

[HuggingFace-dataset](https://huggingface.co/datasets/jingyaogong/minimind_dataset/tree/main)
[百度网盘](https://pan.baidu.com/s/1-Z8Q37lJD4tOKhyBs1D_6Q?pwd=6666)

**Comment by code-monsters-lgl** [comment]
感谢大佬👍👍👍
