### ISSUE TITLE
moe模型如何使用

### ISSUE THREAD

**Issue by WangRongsheng** [jingyaogong/minimind#24]
您好，

我在 https://github.com/jingyaogong/minimind/blob/master/1-pretrain.py#L102 中看到了可以设置使用moe模型，但是直接加载会报错：
```
Traceback (most recent call last):
  File "G:\minimind\1-pretrain.py", line 169, in <module>
    model = init_model(model_type = "moe") # 设置"dense”或者"moe"模型
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\minimind\1-pretrain.py", line 103, in init_model
    state_dict = torch.load(ckp, map_location=device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda3\Lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda3\Lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda3\Lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output/pretrain_moe/pretrain_512_moe.pth'
```

请问如何使用？

**Comment by jingyaogong** [comment]
你贴出的这个是修改版吗

这里如果是为了加载已有的权重续训练，确保 `output/pretrain_moe/pretrain_512_moe.pth`  下面.pth文件的存在

可以在这里先把我的预训练权重文件下载放过去

https://pan.baidu.com/s/11CneDVTkw2Y6lNilQX5bWw?pwd=6666

注释掉就是从头训练 不是在已有权重续训

**Comment by WangRongsheng** [comment]
收到，感谢！
