### ISSUE TITLE
sft_data.csv数据生成报错

### ISSUE THREAD

**Issue by liyu98** [jingyaogong/minimind#72]
当 data_process.py 执行 sft_process(contain_history=True) 报错。

Traceback (most recent call last):
  File "/Users/xxxx/Documents/AI/minimind/data_process.py", line 147, in <module>
    sft_process(contain_history=True)
  File "/Users/xxxx/Documents/AI/minimind/data_process.py", line 101, in sft_process
    process_and_write_data(data)
  File "/Users/xxxx/Documents/AI/minimind/data_process.py", line 78, in process_and_write_data
    df.to_csv(f'./dataset/{file_name}', mode='a', header=False, index=False, lineterminator='\r\n')
  ......
    libwriters.write_csv_rows(
  File "pandas/_libs/writers.pyx", line 72, in pandas._libs.writers.write_csv_rows
_csv.Error: need to escape, but no escapechar set

是需要处理 sft_data_zh.jsonl 的数据还是 导出sft_data.csv的时候，添加分割符。 如果添加了，对后面的训练是否有影响？

**Comment by jingyaogong** [comment]
pandas版本是多少，我无法复现这个问题

**Comment by jingyaogong** [comment]
可以加的，强行转义字符频率很低，应该基本不会受影响

可以pull最新代码process一下

训练后comment效果😊
