### ISSUE TITLE
5-dpo_train运行报错，是版本问题吗？

### ISSUE THREAD

**Issue by bwla** [jingyaogong/minimind#85]
D:\Anaconda3\envs\minni\python.exe D:/work/qyQwen/minimind-master/5-dpo_train.py
Traceback (most recent call last):
  File "D:\work\qyQwen\minimind-master\5-dpo_train.py", line 49, in <module>
    dpo_trainer = DPOTrainer(
  File "D:\Anaconda3\envs\minni\lib\site-packages\**transformers\utils\deprecation.py**", line 165, in wrapped_func
    return func(*args, **kwargs)
**TypeError: __init__() got an unexpected keyword argument 'beta'**

Process finished with exit code 1
transformer=4.46.0和4.44.0都试过，trl=0.11.3

**Comment by jingyaogong** [comment]
版本问题，你需要确认 `所谓"transformer=4.46.0和4.44.0都试过，trl=0.11.3"` 是否来自 `minni` 环境？

召集多人测试了所有不同平台的机器，不可复现，暂时close
